/**
 * Does the editor's background motion still match the client's?
 *
 * The preview is only worth having if it shows what the console will show, and
 * "looks about right" is not a standard anyone can hold code to. So the
 * editor's JS port of theme_motion.cpp is run over a fixed grid of inputs and
 * required to produce, byte for byte, what the C++ produced for the same grid.
 *
 * motion-reference.txt is that C++ output, generated by tests/dump_motion.cpp
 * in the romm-switch-client repo:
 *
 *     g++ -std=c++17 -Isource tests/dump_motion.cpp source/ui/theme_motion.cpp \
 *         source/ui/theme_spec.cpp source/retro/safe_paths.cpp -o /tmp/dump \
 *         && /tmp/dump > ../Theme-App/tests/motion-reference.txt
 *
 * Regenerate it when theme_motion.cpp changes - a diff in this file IS the
 * notification that the editor needs the same change.
 *
 *     node tests/check-motion.mjs
 *
 * Needs playwright (npm i -D playwright) and a Chromium it can launch.
 */
import { chromium } from 'playwright';
import { spawn } from 'node:child_process';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(here, '..');
const PORT = 8789;

const srv = spawn('python3', ['-m', 'http.server', String(PORT), '--bind', '127.0.0.1'],
                  {cwd: root, stdio: 'ignore'});
await new Promise(r => setTimeout(r, 900));

const browser = await chromium.launch({
  executablePath: process.env.CHROMIUM_PATH || undefined,
  args: ['--no-sandbox'],
});
const page = await browser.newPage();
page.on('pageerror', e => { console.error('page error:', e.message); });
await page.goto(`http://127.0.0.1:${PORT}/romm-theme-editor.html`, {waitUntil: 'networkidle'});

/* The grid must stay identical to the one in dump_motion.cpp. */
const got = await page.evaluate(() => {
  const out = [];
  const kinds   = ['none','drift','pan','zoom'];
  const speeds  = [0.1, 0.4, 1.0, 2.5, 8.0];
  const amounts = [0, 1, 7, 24, 32, 64, 133, 256];
  const times   = [0,1,17,250,999,1000,4000,6000,11999,12000,12001,18000,
                   23999,24000,24001,60000,123456,999999,4000000,4294967295];

  for (const k of kinds) for (const sp of speeds) for (const am of amounts) for (const ms of times){
    const p = backgroundPlacement({kind:k, speed:sp, amount:am}, ms);
    const covers = (p.x <= 0 && p.y <= 0 && p.x + p.w >= 1280 && p.y + p.h >= 720) ? 1 : 0;
    out.push(`P|${k}|${sp}|${am}|${ms}|${p.x}|${p.y}|${p.w}|${p.h}|${covers}`);
  }
  const frameCounts = [0,1,2,8,30,60,240], fpsv = [1,7,10,12,24,30,60];
  for (const loop of [0,1]) for (const fc of frameCounts) for (const f of fpsv) for (const ms of times){
    out.push(`F|${loop}|${fc}|${f}|${ms}|` +
             animationFrame({kind:'sheet', frames:fc, fps:f, loop: loop !== 0}, ms));
  }
  const fw = [1,16,320,640], sizes = [0,100,320,640,1280,1281,2560];
  for (const w of fw) for (const sw of sizes) for (const sh of sizes) for (const fr of [0,1,3,8,47,200]){
    const a = {kind:'sheet', fw:w, fh: Math.trunc(w/2) > 0 ? Math.trunc(w/2) : 1};
    const r = sheetSource(a, fr, sw, sh);
    out.push(`S|${w}|${a.fh}|${sw}|${sh}|${fr}|${r.x}|${r.y}|${r.w}|${r.h}|` +
             sheetCapacity(a, sw, sh));
  }
  return out;
});

await browser.close();
srv.kill();

const ref = readFileSync(path.join(here, 'motion-reference.txt'), 'utf8').trim().split('\n');
let bad = 0, shown = 0;
if (ref.length !== got.length){
  console.error(`row count differs: reference ${ref.length}, editor ${got.length}`);
  bad++;
}
for (let i = 0; i < Math.min(ref.length, got.length); i++){
  if (ref[i] !== got[i]){
    bad++;
    if (shown++ < 10) console.error(`line ${i+1}\n  client ${ref[i]}\n  editor ${got[i]}`);
  }
}
const uncovered = ref.filter(l => l.startsWith('P|') && l.endsWith('|0')).length;
console.log(`${Math.min(ref.length, got.length)} rows compared`);
console.log(uncovered
  ? `WARNING: ${uncovered} placements leave part of the screen uncovered`
  : 'every placement covers the full 1280x720 screen');
console.log(bad ? `FAILED: ${bad} mismatches` : 'OK: the editor matches theme_motion.cpp exactly');
process.exit(bad ? 1 : 0);
