/**
 * Does the editor's focus effect still match the client's?
 *
 * Same standard as check-motion.mjs, for the same reason: a preview that runs
 * its own approximation is worse than no preview, because it looks
 * authoritative while being wrong. So the editor's JS port of
 * theme_effects.cpp is run over a fixed grid and required to produce, bit for
 * bit, what the C++ produced for the same grid. Floats are compared as their
 * raw 32-bit patterns rather than as printed decimals: a decimal has to be
 * rounded, and C and JavaScript break a tie in opposite directions, which
 * turns eight identical numbers into eight "mismatches".
 *
 * effects-reference.txt is that C++ output, generated by tests/dump_effects.cpp
 * in the romm-switch-client repo:
 *
 *     g++ -std=c++17 -Isource -Itests/stubs tests/dump_effects.cpp \
 *         source/ui/theme_effects.cpp -o /tmp/dumpfx \
 *         && /tmp/dumpfx > ../Theme-App/tests/effects-reference.txt
 *
 * Regenerate it when theme_effects.cpp changes - a diff in this file IS the
 * notification that the editor needs the same change.
 *
 *     node tests/check-effects.mjs
 *
 * Needs playwright (npm i -D playwright) and a Chromium it can launch.
 */
import { chromium } from 'playwright';
import { spawn } from 'node:child_process';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(here, '..');
const PORT = 8791;

const srv = spawn('python3', ['-m', 'http.server', String(PORT), '--bind', '127.0.0.1'],
                  {cwd: root, stdio: 'ignore'});
await new Promise(r => setTimeout(r, 900));

const browser = await chromium.launch({
  executablePath: process.env.CHROMIUM_PATH || undefined,
  args: ['--no-sandbox'],
});
const page = await browser.newPage();
page.on('pageerror', e => { console.error('page error:', e.message); });
await page.goto(`http://127.0.0.1:${PORT}/romm-theme-editor.html`, {waitUntil: 'networkidle'});

/* Both grids must stay identical to the ones in dump_effects.cpp. */
const got = await page.evaluate(() => {
  const out = [];
  /* The same 32-bit pattern the C++ memcpy'd out of its float. */
  const fbuf = new Float32Array(1), ibuf = new Uint32Array(fbuf.buffer);
  const bits = v => { fbuf[0] = v; return (ibuf[0] >>> 0).toString(16).padStart(8, '0'); };
  const kinds = ['none','smoke','embers','glow','shimmer','pulse','fade'];

  for (const k of kinds)
    for (const sp of [0.1, 0.4, 1.0, 2.5, 8.0])
      for (const am of [0, 1, 40, 55, 100])
        for (const ms of [0,1,17,1000,4000,11999,12000,24000,60000,
                          123456,999999,4294967295]){
          const fx = {kind:k, speed:sp, amount:am};
          const o = effectOutline(fx, ms);
          out.push(`O|${k}|${sp}|${am}|${ms}|${o.alpha}|${o.extra}|` +
                   `${bits(o.highlight)}|${bits(o.span)}|${effectHalo(fx, ms)}`);
        }

  const rects = [{x:0,y:0,w:0,h:0}, {x:10,y:10,w:1,h:1},
                 {x:268,y:158,w:268,h:214}, {x:0,y:0,w:1280,h:720}];
  for (const k of kinds)
    for (const sp of [0.1, 1.0, 8.0])
      for (const am of [0, 1, 40, 100])
        for (const ms of [0, 17, 1000, 11999, 123456, 4294967295])
          for (let ri = 0; ri < rects.length; ri++){
            const ps = effectParticles({kind:k, speed:sp, amount:am}, rects[ri], ms);
            out.push(`N|${k}|${sp}|${am}|${ms}|${ri}|${ps.length}`);
            ps.forEach((p, i) => out.push(
              `P|${k}|${sp}|${am}|${ms}|${ri}|${i}|` +
              `${bits(p.x)}|${bits(p.y)}|${bits(p.radius)}|${p.alpha}`));
          }
  return out;
});

await browser.close();
srv.kill();

const ref = readFileSync(path.join(here, 'effects-reference.txt'), 'utf8').trim().split('\n');
let bad = 0, shown = 0;
if (ref.length !== got.length){
  console.error(`row count differs: reference ${ref.length}, editor ${got.length}`);
  bad++;
}
for (let i = 0; i < Math.min(ref.length, got.length); i++){
  if (ref[i] !== got[i]){
    bad++;
    if (shown++ < 10) console.error(`line ${i+1}\n  client ${ref[i]}\n  editor ${got[i]}`);
  }
}

/* The invariants the C++ tests assert, re-checked against the reference so a
   regenerated file that broke one of them cannot slip through here either. */
let capped = 0, escaped = 0, badAlpha = 0;
for (const line of ref){
  const f = line.split('|');
  if (f[0] === 'N' && Number(f[6]) > 48) capped++;
  if (f[0] === 'P'){
    const a = Number(f[10]);
    if (a < 0 || a > 255) badAlpha++;
  }
  if (f[0] === 'O'){
    const a = Number(f[5]);
    if (a < 0 || a > 255) badAlpha++;
    if (Number(f[9]) > 26) escaped++;
  }
}
console.log(`${Math.min(ref.length, got.length)} rows compared`);
if (capped)   { console.error(`FAILED: ${capped} frames exceed the 48-particle cap`); bad += capped; }
if (escaped)  { console.error(`FAILED: ${escaped} halos exceed the 26px bleed budget`); bad += escaped; }
if (badAlpha) { console.error(`FAILED: ${badAlpha} alphas outside 0-255`); bad += badAlpha; }
if (!capped && !escaped && !badAlpha){
  console.log('cap, bleed budget and alpha range all hold');
}
console.log(bad ? `FAILED: ${bad} mismatches` : 'OK: the editor matches theme_effects.cpp exactly');
process.exit(bad ? 1 : 0);
